/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MigrationsRouteImport } from './routes/migrations'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsFilenameRouteImport } from './routes/docs.$filename'

const MigrationsRoute = MigrationsRouteImport.update({
  id: '/migrations',
  path: '/migrations',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsFilenameRoute = DocsFilenameRouteImport.update({
  id: '/docs/$filename',
  path: '/docs/$filename',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/migrations': typeof MigrationsRoute
  '/docs/$filename': typeof DocsFilenameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/migrations': typeof MigrationsRoute
  '/docs/$filename': typeof DocsFilenameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/migrations': typeof MigrationsRoute
  '/docs/$filename': typeof DocsFilenameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/features' | '/migrations' | '/docs/$filename'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/features' | '/migrations' | '/docs/$filename'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/features'
    | '/migrations'
    | '/docs/$filename'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FeaturesRoute: typeof FeaturesRoute
  MigrationsRoute: typeof MigrationsRoute
  DocsFilenameRoute: typeof DocsFilenameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/migrations': {
      id: '/migrations'
      path: '/migrations'
      fullPath: '/migrations'
      preLoaderRoute: typeof MigrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$filename': {
      id: '/docs/$filename'
      path: '/docs/$filename'
      fullPath: '/docs/$filename'
      preLoaderRoute: typeof DocsFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FeaturesRoute: FeaturesRoute,
  MigrationsRoute: MigrationsRoute,
  DocsFilenameRoute: DocsFilenameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
